### ISSUE TITLE
Mailbox XP Calculator

### ISSUE THREAD

**Issue by PowerShellJC** [ComputingwithCody/NoBonusXP#1]
Just wondering if there is a way to display a calculation on the mailbox based on how much XP is in the mailbox, how much your current cloak bonus XP is and what level you would be if you looted the mailbox right now? Would be super helpful on min maxing how many more dungeons to do for tokens or if you need one more raids worth of XP threads.

**Comment by ComputingwithCody** [comment]
That is something, I am working on, no eta at the moment.
